webdriver.version=LOCAL

accept.insecure.certs=true
accept.ssl.certs=true
implicit.wait.sec=0
page.wait.sec=500

# We point the base URL directly to the folder containing the sub-elements
webdriver.download.url=file:///C:/temp/cpin_downloads
webdriver.filename=msedgedriver
# FORCE A MOCK EXTENSION HERE so the output stream builds a file path (e.g. .../LOCAL/msedgedriver.zip)
webdriver.zip.filename.win=msedgedriver.zip
webdriver.system.property.name=webdriver.edge.driver